### PR TITLE
[162] Find OpenAlex concepts related to food tech

### LINKED ISSUE #162: Checking OpenAlex concepts that are related to food innovations
We would like to find concepts in OpenAlex (that they use to tag publications) that are related to our food innovations taxonomy.

The list of concepts can be found [here](https://docs.google.com/spreadsheets/d/1LBFHjPt4rj_9r0t0TTAlT68NwOtNH8Z21lBMsJDMoZg/edit#gid=269244404), and more background information on the concepts is [here](https://docs.google.com/document/d/1q3jBlEexskCZaSafFDMEEY3naTeyd7GS/edit#heading=h.gjdgxs).

This issue could cover:
- Preparing a list of OpenAlex concepts that correspond to our food tech taxonomy
  - I will properly share the table with the taxonomy and related terms ASAP, but for now I've copied the taxonomy below.

Later on (but not in this issue) we could then use the concepts to fetch training data for the model(s).

To quickly find the most relevant OpenAlex concepts from that long list that I've shared above, I think we can actually calculate embeddings using eg Sentence-BERT, and use semantic similarity. For example, one could do the following:
1. Calculate embeddings for all OpenAlex concepts
2. Check most similar embeddings for all our food tech taxonomy Major and Minor category titles and their related terms
3. Find top matches from OpenAlex to each of our terms
4. Perhaps check also the OpenAlex's related terms to the top matches as there are quite a few and they might be useful. For example, check concepts related to the "obesity" concept. Not sure, but I guess we'd need to use OpenAlex's API for this?
5. Manually review the list (I and other colleagues can help with that)

[I've written a module](https://github.com/nestauk/innovation_sweet_spots/blob/dev/innovation_sweet_spots/utils/embeddings_utils.py) that helps to deal with simple embeddings operations (eg, easily calculate, save the embeddings, query the most similar embeddings to arbitrary terms) - I just need to merge some changes to the module from another in-progress branch into dev. I will try to do that ASAP.

Here is the present version of the food tech taxonomy. It has two levels, Major and Minor, and each Minor level is associated with a few additional terms. These terms in fact correspond to tags and industry names used by the Dealroom business platform.
```
taxonomy = {
    "health": {
        "health (all other)": [
            "health",
            "personal health",
            "health care",
            "healthcare",
            "health and wellness",
        ],
        "diet": [
            "diet",
            "weight management",
            "diet personalization",
        ],
        "dietary supplements": ["dietary supplements", "probiotics"],
        "health tech": [
            "health platform",
            "medical devices",
            "medical device",
            "tech for patients",
            "digital healthcare",
            "health diagnostics",
            "health information",
            "medical technology",
            "healthtech",
            "digital health",
            "digital therapeutics",
        ],
        "biomedical": [
            "obesity",
            "diabetes",
            "disease",
            "allergies",
            "chronic disease",
            "gastroenterology",
            "cardiology",
            "medical",
            "pharmaceutical",
            "therapeutics",
        ],
    },
    "innovative food": {
        "innovative food (all other)": [
            "innovative food", 
        ],
        "alt protein": [
            "enabler of alternative proteins",
            "alternative protein",
            "meat substitute",
            "dairy substitute",
            "alternative dairy",
            "seafood substitute",
            "insect",
            "plant-based",
        ],
        "fermentation": ["fermentation"],
        "vegan": ["vegan"],
        "plant-based": ["plant-based"],
        "taste": [
            "taste",
            "flavor",
        ],
        "algae": ["algae"],
        "oleaginous": ["oleaginous"],
    },
    "logistics": {
        "logistics (all other)": [
            "logistic",
            "logistics",
            "logistics tech",
            "logistics solutions",
            "freight",
            "warehousing",
            "fleet management",
            "order management",
            "shipping",
        ],
        "supply chain": [
            "supply chain management",
        ],
        "delivery": [
            "delivery",
            "food delivery platform",
            "food delivery service",
            "last-mile delivery",
            "10 min delivery",
            "food logistics & delivery",
            "logistics & delivery", 
        ],
        "meal kits": [
            "subscription boxes",
            "meal kits",
        ],
    },
    "cooking and kitchen": {
        "kitchen tech": [
            "kitchen & cooking tech",
            "cooking tech",
        ],
        "dark kitchen": [
            "dark kitchen",
        ],
    },
    "agritech": {
        "agritech (all other)": [
            "agritech",
            "novel farming",
            "hydroponics",
            "fertigation",
        ],
        "crop protection": [
            "crop protection",
            "pesticides",
            "pest control",
        ],
        "precision agriculture": ["precision agriculture"],
        "vertical farming": ["vertical farming"],
    },
    "food waste": {
        "food waste (all other)": [
            "organic waste",
            "food waste",
            "waste solution",
            "waste reduction",
            "waste management",
        ],
        "packaging": [
            "packaging and containers",
            "packaging",
            "packaging solutions",
            "food packaging",
        ],
    },
    "retail and restaurants": {
        "retail and restaurant tech (all other)": [
            "in-store retail & restaurant tech",
            "restaurant tech",
        ],
        "restaurant management": [
            "restaurants management",
            "restaurant reservation",
        ],
    },
}
```

### PR DESCRIPTION
**Pull request by beingkk**
Closes #162 

---

Checklist:

- [ ] I have refactored my code out from `notebooks/`
- [ ] I have checked the code runs
- [ ] I have tested the code
- [ ] I have run `pre-commit` and addressed any issues not automatically fixed
- [ ] I have merged any new changes from `dev`
- [ ] I have documented the code
  - [ ] Major functions have docstrings
  - [ ] Appropriate information has been added to `README`s
- [ ] I have explained the feature in this PR or (better) in `output/reports/`
- [ ] I have requested a code review

### CODE REVIEW

**Comment by beingkk** [comment]
Hi Adeola [@dede95], this is the beginning of the PR for the issue to find OpenAlex concepts relevant to the food tech project. As we discussed, I've started on this a little bit to show how the embedding utils work. I've produced vectorised representations of the OpenAlex concepts - this should allow quickly finding most related concepts to our food tech category labels.

You can continue in the notebook that I've started: `innovation_sweet_spots/analysis/notebooks/foodtech/open_alex/2022_07_27_OpenAlex_concepts.py` (you'll need to use jupytext to convert it from .py to .ipynb)

To run the notebook, you'll need to also download the OpenAlex concept spreadsheet and food tech taxonomy. You can do that by running the following commands from the terminal, from the repo root directory.
```
aws s3 sync s3://innovation-sweet-spots-lake/inputs/data/openAlex inputs/data/openAlex  
```

```
aws s3 sync s3://innovation-sweet-spots-lake/outputs/foodtech/interim outputs/foodtech/interim 
```

You'll need to then generate the embeddings by running this from the command line, from the root directory of the repo.
```
python innovation_sweet_spots/pipeline/foodtech/generate_embeddings_OpenAlex_concepts.py
```

Alternatively, you can also download the computed embeddings from s3 (I've synced them already)
```
aws s3 sync s3://innovation-sweet-spots-lake/outputs/preprocessed/embeddings outputs/preprocessed/embeddings 
```

Once you have all these inputs sorted, you should be able to use the notebook `2022_07_27_OpenAlex_concepts`.

Don't hesitate if you have any questions, and happy to discuss more, later this Friday!

**Comment by beingkk** [comment]
Just in case it's useful, here's also a link to a Google Sheet with present version of the food tech [taxonomy](https://docs.google.com/spreadsheets/d/1rB3Fs_rOBUGT1NHRWitojGjHkZDygduKVzfE1qroQow/edit#gid=408372646) and labels!

**Comment by beingkk** [comment]
Hey @dede95 , it was nice catching up! 

As discussed, I think the most useful output would be a table with the following columns:
- column 1 with food tech taxonomy’s category names and labels 
- column 2 with the potentially relevant OpenAlex concept for each of the words or phrases from column 1
- column 3 with the similarity score

I guess, for each unique word or phrase from column 1, we could have around 10-20 potentially relevant OpenAlex concepts to review. Perhaps try it out a bit and see what number feels appropriate.

We could then put this on google sheets review together.

Don't hesitate if you have more questions!

**Comment by beingkk** [comment]
Hey @dede95 I'm not sure where we left with this PR - do you think it's OK to merge in dev?

**Review by dede95 — COMMENTED** [review]
@beingkk Included `2022_08_12_OpenAlex_concepts_all_terms.py` from the work that was done.

**Pull request merged**
