### PR TITLE
[134] Add founder variables to investments predictions dataset creation

### LINKED ISSUE #134: Add founder variables to investments predictions dataset

### PR DESCRIPTION
**Pull request by Jack-0-0**
Closes #134.

This PR adds variables to the investments predictions dataset for:
* `founder_count`
* `male_founder_percentage`
* `founder_max_degrees`
* `founder_mean_degrees`

This PR also:
* Adds a test mode to run the script with a small dataset
*  Makes changes to allow use of both 2021 and the new 2022 crunchbase data in the dataset creation

### CODE REVIEW

**Comment by Jack-0-0** [comment]
It would have been nice to add a variable for if the founders had founded another company. However, strangely(?) in the `crunchbase_people` file the `id` (for person) only relates to 1 company max.

**Comment by Jack-0-0** [comment]
Currently, there is only founder information for about 20% of companies in the dataset. The method I have used to identify founders is by looking for people with the word `founder` in their `featured_job_title` in the `crunchbase_people` file.

I suppose part of the cause for the low amount of founder information being found is that founders will sometimes list themselves as a director rather a founder (being in the UK). We could select for founders using `founder` and `director` but that would bring it a lot of false positives. Do you have any ideas on how to improve this?

**Comment by beingkk** [comment]
Hi @Jack-0-0 , thanks a lot for this! I merged the updated `dev` branch with the adjusted getters (that restore the column names of the new data snapshot) into this branch - hope that's OK! I then tried running `create_dataset.py` with both the updated data, and the previous version of the data. 

With the previous version it worked fine (I checked the test mode).

With the new data, it sill threw an error even after updating the getters. It looks like in the new version, there are unfortunately missing columns in the `crunchbase_people` table: specifically `location_id` and `country` columns.

```
/Users/karliskanders/Documents/innovation_sweet_spots/innovation_sweet_spots/pipeline/pilot/investment_predictions/create_dataset/utils.py:92: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  group_dummies = pd.get_dummies(cb_orgs["groups"].explode()).sum(level=0)
Traceback (most recent call last):
  File "innovation_sweet_spots/pipeline/pilot/investment_predictions/create_dataset/create_dataset.py", line 325, in <module>
    typer.run(create_dataset)
  File "/Users/karliskanders/opt/miniconda3/envs/iss_dev_test/lib/python3.7/site-packages/typer/main.py", line 859, in run
    app()
  File "/Users/karliskanders/opt/miniconda3/envs/iss_dev_test/lib/python3.7/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/karliskanders/opt/miniconda3/envs/iss_dev_test/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/karliskanders/opt/miniconda3/envs/iss_dev_test/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/karliskanders/opt/miniconda3/envs/iss_dev_test/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/karliskanders/opt/miniconda3/envs/iss_dev_test/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/karliskanders/opt/miniconda3/envs/iss_dev_test/lib/python3.7/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "innovation_sweet_spots/pipeline/pilot/investment_predictions/create_dataset/create_dataset.py", line 172, in create_dataset
    )[PEOPLE_COLS]
  File "/Users/karliskanders/opt/miniconda3/envs/iss_dev_test/lib/python3.7/site-packages/pandas/core/frame.py", line 3464, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]
  File "/Users/karliskanders/opt/miniconda3/envs/iss_dev_test/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/Users/karliskanders/opt/miniconda3/envs/iss_dev_test/lib/python3.7/site-packages/pandas/core/indexing.py", line 1377, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['person_country', 'location_id'] not in index"
```

That's annoying - I guess there might be two options. Either Crunchbase removed those columns for whatever reason, or perhaps they've been lost when Jack Vines updated the data? Perhaps you can reach out to Jack to check in about this?

Alternatively, perhaps you don't need the country and location_id data for people?

Finally, to answer your question about the lack of founder data for all companies: Perhaps we don't want to restrict this type of feature only to founders but include all staff listed on Crunchbase? Presumably, Crunchbase only lists senior staff members, so that could be quite relevant. I guess, it might be as easy as removing the criteria that the person needs to be a founder?

**Comment by Jack-0-0** [comment]
Thank you for reviewing and updating the getters @beingkk.

I have removed `country` and `location_id` for people. `create_dataset.py` should now work with both the crunchbase 2021 and 2022 data.

> Finally, to answer your question about the lack of founder data for all companies: Perhaps we don't want to restrict this type of feature only to founders but include all staff listed on Crunchbase? Presumably, Crunchbase only lists senior staff members, so that could be quite relevant. I guess, it might be as easy as removing the criteria that the person needs to be a founder?

The issue with using all staff is that in the data it is not clear when the staff joined the company. So if we include all staff it could be giving the model data from the future. With founders we can assume they were there when the company was started.

**Review by beingkk — APPROVED** [review]
Thank you @Jack-0-0 ! I tested it with the new data and it appears to work.

Also excellent point about the issue with including all staff - let's leave only founders then, as you've originally proposed.

**Pull request merged**
