### PR TITLE
[59] Crunchbase data wrangler

### LINKED ISSUE #48: CurrencyConverter package is missing from requirements.txt
CurrencyConverter package is missing from requirements.txt

### LINKED ISSUE #59: Add `CrunchbaseWrangler` to `wrangling_utils`
Similarly to `GtrWrangler` there should be class allowing to quickly get CB organisation investment rounds (deals)

### PR DESCRIPTION
**Pull request by beingkk**
Closes #59 
Closes #48 

Added functions to find deal data for any list of CB companies. The usage is as follows:

```python
from innovation_sweet_spots.analysis.wrangling_utils import CrunchbaseWrangler
from innovation_sweet_spots.getters import crunchbase as cb

CbWrangler = CrunchbaseWrangler()

# Fetch a test list of Crunchbase organisations 
cb_orgs = cb.get_crunchbase_orgs(nrows=100)

cb_deals = CbWrangler.get_funding_rounds(cb_orgs)
```
cb_orgs is a dataframe that must have CB `id` and `name` columns
cb_deals will return (among other columns) `raised_amount_gbp`

Added one very basic unit test for the currency converter. 
Won't bother at the moment to add test for the `CrunchbaseWrangler.get_funding_rounds` function, as it's quite messy to create all the mock dataframes - need to read up on how to do this more neatly... (any suggestions welcome, @Jack-0-0)

FYI I will also add other functions to this class (in another PR) for getting:
- investor data for each deal
- industry tags for each company

---

Checklist:

- [x] I have refactored my code out from `notebooks/`
- [x] I have checked the code runs
- [x] I have tested the code
- [x] I have run `pre-commit` and addressed any issues not automatically fixed
- [x] I have merged any new changes from `dev`
- [x] I have documented the code
  - [x] Major functions have docstrings
  - [ ] Appropriate information has been added to `README`s
- [x] I have explained the feature in this PR or (better) in `output/reports/`
- [x] I have requested a code review

### CODE REVIEW

**Comment by beingkk** [comment]
FYI @Jack-0-0 in case you already need to access funding round data (will aim to finish the PR by Thursday)

**Comment by beingkk** [comment]
Hi @Jack-0-0 , happy for you to check this PR whenever you have time!

**Review by Jack-0-0 — APPROVED** [review]
Thanks for this @beingkk. `CbWrangler.get_funding_rounds` runs as expected and the code looks good to merge!

For mocking in the unit tests, you could use the [mock functionality in unittest](https://docs.python.org/3/library/unittest.mock.html).

**Comment by beingkk** [comment]
Thank you @Jack-0-0 !

**Pull request merged**
