### PR TITLE
[137] Location-related features for investments predictions 

### LINKED ISSUE #137: Create additional location related features for investments predictions dataset
It would be good to create additional location related features for the investments predictions dataset using data from the [BEIS indicators](https://github.com/nestauk/beis-indicators).

This would require matching Crunchbase location information with the regions used in the BEIS indicators.

The BEIS data uses locations in either NUTS2, NUTS3 or LEP structure.

Currently the investment predctions dataset is using `location_id` from Crunchbase for each company. This is in the format city_country, for example `oxford_united-kingdom`.

We could use a different Crunchbase location variable if it is easier to join to the BEIS data.   In Crunchbase there is postcode but that is missing for about a third of the companies.

From a quick first look it seems that the Crunchbase `location_id` variable is potentially at too low of a level. It may be better to use the Crunchbase variable `region`. The `region` variable seems to have the value `England` when it should be `London` so it could make sense to reassign `England` to `London`.

To download the BEIS data you can access it either on [ Github](https://github.com/nestauk/beis-indicators/tree/dev/ds/data/processed) or from the [government website](https://access-research-development-spatial-data.beis.gov.uk/indicators) (click download on the top right).

### PR DESCRIPTION
**Pull request by beingkk**
Closes #137  

- Adds a script to create a csv file with Crunchbase organisations and R&D indicators  of their locations. 
- Also, adds a utility function to geolocate any address using Bing API (not used in the final script)

Usage:
```
python innovation_sweet_spots/pipeline/pilot/investment_predictions/create_dataset/create_beis_indicators.py --help
```

The R&D indicators are sourced from the [Nesta/BEIS R&D dashboard](https://access-research-development-spatial-data.beis.gov.uk/indicators). The script will download the data if it doesn't exist locally.

This script makes use of a previously prepared dictionary mapping Crunchbase `location_id` to NUTS2 codes. This allows to map 99% of the UK companies in the Crunchbase data to NUTS2. You'll need to download the file `cb_geos.json` from s3 and place it into `inputs/data/misc/geo`

The remaining 1% could be mapped via postcodes or addresses, to longitude and latitude, and then to NUTS2 (not implemented in the final script; some early work is in the prototyping notebook which is included in this PR for completeness).

No need to review the prototyping notebook `innovation_sweet_spots/analysis/prototyping/2022_04_08_beis_indicators.py` - I've just left it in this PR as there is some code to geolocate companies via their postcodes and addresses, that might become useful later down the line.

@Jack-0-0: please feel free to adjust the script so that it fits with the rest of your pipeline.
In terms of which features to actually use in the final model: I guess we could first try all of them?

I think there might be some interesting issues with the fact that London area appears to be divided into smaller NUTS2 regions that can have considerably different values (eg the number of STEM professionals). Presumably, a London startup in a NUTS2 region with a smaller RnD value will still benefit from the RnD happening in the rest of the London regions.

---

Checklist:

- [x] I have refactored my code out from `notebooks/`
- [x] I have checked the code runs
- [x] I have tested the code
- [x] I have run `pre-commit` and addressed any issues not automatically fixed
- [x] I have merged any new changes from `dev`
- [x] I have documented the code
  - [x] Major functions have docstrings
  - [ ] Appropriate information has been added to `README`s
- [x] I have explained the feature in this PR or (better) in `output/reports/`
- [x] I have requested a code review

### CODE REVIEW

**Comment by Jack-0-0** [comment]
Thank you very much for implementing this @beingkk.

I had an issue when running `python innovation_sweet_spots/pipeline/pilot/investment_predictions/create_dataset/create_beis_indicators.py`
as it tried to load a bing API key from .env when it runs the `utils/geo` file.
Locally, I just commented out the `geolocate_address` function and the bing/env constants at the top to allow `create_beis_indicators.py` to run. Maybe this functionality could be moved to another file as it is not being used currently?
 
I made a couple of minor changes to remove an unused f string and int().

**Comment by beingkk** [comment]
Thank you for checking and making the adjustments! I've added a quick fix by commenting out the lines and added an issue to deal with this properly  a bit later. Hope that works for now!

Happy to merge if you think it's good enough (or happy also to let you integrate further with the main feature engineering pipeline).

**Comment by Jack-0-0** [comment]
It looks good to merge 👍

I think it's nice to keep `create_beis_indicators.py` on its own rather than integrating into `investment_predictions/create_dataset.py` as it could be used on it own for different analysis.

**Review by Jack-0-0 — APPROVED** [review]

**Comment by beingkk** [comment]
Thank you @Jack-0-0 !

**Pull request merged**
